apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.action.triggered
      requests:
        - "curl --request POST --data '{{{.data.problem}}  \"action\":
          \"{{.data.action.action}}\"}'
          https://webhook.site/48f1ba78-10f7-4b01-8c4c-ade04d3d0e40"
      subscriptionID: 9441d564-0c5b-47ed-83be-6a3969c94fc5
      sendFinished: true
